{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_python_file.py:10: AssertionError"}, "description": "this test fails", "start": 1607342820720, "stop": 1607342820721, "uuid": "95fc72c2-37b5-4f25-a6e0-8e6d64b4ad40", "historyId": "a6995d17bfce27ae2c7590383534e3f1", "testCaseId": "ab0eaa7fbc08e92afcd3002924b4753b", "fullName": "test_python_file#test_failure", "labels": [{"name": "suite", "value": "test_python_file"}, {"name": "host", "value": "yuanmengdeMacBook-Air.local"}, {"name": "thread", "value": "57527-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_python_file"}]}